// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternshipManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250826083044_init_schema_and_seed")]
    partial class init_schema_and_seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternshipManagement.Models.AppUser", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("passwordhash");

                    b.HasKey("Code", "Role");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("InternshipManagement.Models.DeTai", b =>
                {
                    b.Property<string>("MaDt")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .HasColumnName("madt");

                    b.Property<byte>("HocKy")
                        .HasColumnType("tinyint")
                        .HasColumnName("hocky");

                    b.Property<int?>("KinhPhi")
                        .HasColumnType("int")
                        .HasColumnName("kinhphi");

                    b.Property<int>("MaGv")
                        .HasColumnType("int")
                        .HasColumnName("magv");

                    b.Property<short>("NamHoc")
                        .HasColumnType("smallint")
                        .HasColumnName("namhoc");

                    b.Property<string>("NoiThucTap")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NoiThucTap");

                    b.Property<int>("SoLuongToiDa")
                        .HasColumnType("int")
                        .HasColumnName("soluongtoida");

                    b.Property<string>("TenDt")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tendt");

                    b.HasKey("MaDt");

                    b.HasIndex("MaGv", "NamHoc", "HocKy");

                    b.ToTable("DeTai");

                    b.HasData(
                        new
                        {
                            MaDt = "DT001",
                            HocKy = (byte)1,
                            KinhPhi = 10,
                            MaGv = 1,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty FPT Software",
                            SoLuongToiDa = 2,
                            TenDt = "Hệ thống quản lý sinh viên"
                        },
                        new
                        {
                            MaDt = "DT002",
                            HocKy = (byte)2,
                            KinhPhi = 15,
                            MaGv = 1,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty VNPT",
                            SoLuongToiDa = 3,
                            TenDt = "Ứng dụng web thương mại điện tử"
                        },
                        new
                        {
                            MaDt = "DT003",
                            HocKy = (byte)3,
                            KinhPhi = 20,
                            MaGv = 1,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty Viettel",
                            SoLuongToiDa = 1,
                            TenDt = "AI gợi ý đề tài nghiên cứu"
                        },
                        new
                        {
                            MaDt = "DT004",
                            HocKy = (byte)1,
                            KinhPhi = 12,
                            MaGv = 2,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty EVN",
                            SoLuongToiDa = 3,
                            TenDt = "Phát triển hệ thống IoT giám sát môi trường"
                        },
                        new
                        {
                            MaDt = "DT005",
                            HocKy = (byte)2,
                            KinhPhi = 18,
                            MaGv = 2,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty Mobifone",
                            SoLuongToiDa = 2,
                            TenDt = "Ứng dụng phân tích dữ liệu lớn"
                        },
                        new
                        {
                            MaDt = "DT006",
                            HocKy = (byte)3,
                            KinhPhi = 8,
                            MaGv = 2,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty VNG",
                            SoLuongToiDa = 1,
                            TenDt = "Ứng dụng di động quản lý y tế"
                        },
                        new
                        {
                            MaDt = "DT007",
                            HocKy = (byte)1,
                            KinhPhi = 9,
                            MaGv = 3,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty Hóa chất Việt Nam",
                            SoLuongToiDa = 2,
                            TenDt = "Nghiên cứu vật liệu mới"
                        },
                        new
                        {
                            MaDt = "DT008",
                            HocKy = (byte)2,
                            KinhPhi = 14,
                            MaGv = 3,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty Sơn Hà",
                            SoLuongToiDa = 3,
                            TenDt = "Quy trình sản xuất hóa chất xanh"
                        },
                        new
                        {
                            MaDt = "DT009",
                            HocKy = (byte)3,
                            KinhPhi = 11,
                            MaGv = 3,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty Nước sạch Hà Nội",
                            SoLuongToiDa = 1,
                            TenDt = "Xử lý nước thải công nghiệp"
                        },
                        new
                        {
                            MaDt = "DT010",
                            HocKy = (byte)1,
                            KinhPhi = 7,
                            MaGv = 4,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty Hóa chất Việt Nam",
                            SoLuongToiDa = 2,
                            TenDt = "Nghiên cứu xúc tác hữu cơ"
                        },
                        new
                        {
                            MaDt = "DT011",
                            HocKy = (byte)2,
                            KinhPhi = 13,
                            MaGv = 4,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty Nhựa Bình Minh",
                            SoLuongToiDa = 3,
                            TenDt = "Sản xuất nhựa sinh học"
                        },
                        new
                        {
                            MaDt = "DT012",
                            HocKy = (byte)3,
                            KinhPhi = 19,
                            MaGv = 4,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty Môi trường Đô thị Hà Nội",
                            SoLuongToiDa = 1,
                            TenDt = "Xử lý rác thải đô thị"
                        },
                        new
                        {
                            MaDt = "DT013",
                            HocKy = (byte)1,
                            KinhPhi = 6,
                            MaGv = 5,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty KPMG Việt Nam",
                            SoLuongToiDa = 2,
                            TenDt = "Phân tích tài chính doanh nghiệp"
                        },
                        new
                        {
                            MaDt = "DT014",
                            HocKy = (byte)2,
                            KinhPhi = 11,
                            MaGv = 5,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty Deloitte Việt Nam",
                            SoLuongToiDa = 3,
                            TenDt = "Hệ thống kế toán quản trị"
                        },
                        new
                        {
                            MaDt = "DT015",
                            HocKy = (byte)3,
                            KinhPhi = 17,
                            MaGv = 5,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty PwC Việt Nam",
                            SoLuongToiDa = 1,
                            TenDt = "Ứng dụng Blockchain trong kế toán"
                        },
                        new
                        {
                            MaDt = "DT016",
                            HocKy = (byte)1,
                            KinhPhi = 10,
                            MaGv = 6,
                            NamHoc = (short)2025,
                            NoiThucTap = "Ngân hàng Vietcombank",
                            SoLuongToiDa = 2,
                            TenDt = "Phân tích rủi ro tài chính"
                        },
                        new
                        {
                            MaDt = "DT017",
                            HocKy = (byte)2,
                            KinhPhi = 14,
                            MaGv = 6,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty Chứng khoán SSI",
                            SoLuongToiDa = 3,
                            TenDt = "Dự báo thị trường chứng khoán"
                        },
                        new
                        {
                            MaDt = "DT018",
                            HocKy = (byte)3,
                            KinhPhi = 20,
                            MaGv = 6,
                            NamHoc = (short)2025,
                            NoiThucTap = "Ngân hàng BIDV",
                            SoLuongToiDa = 1,
                            TenDt = "Ứng dụng AI trong ngân hàng"
                        },
                        new
                        {
                            MaDt = "DT019",
                            HocKy = (byte)1,
                            KinhPhi = 18,
                            MaGv = 7,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty VinFast",
                            SoLuongToiDa = 2,
                            TenDt = "Thiết kế robot công nghiệp"
                        },
                        new
                        {
                            MaDt = "DT020",
                            HocKy = (byte)2,
                            KinhPhi = 9,
                            MaGv = 7,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty Cơ khí Hà Nội",
                            SoLuongToiDa = 3,
                            TenDt = "Gia công cơ khí chính xác"
                        },
                        new
                        {
                            MaDt = "DT021",
                            HocKy = (byte)3,
                            KinhPhi = 12,
                            MaGv = 7,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty SamSung Việt Nam",
                            SoLuongToiDa = 1,
                            TenDt = "Ứng dụng CAD/CAM trong sản xuất"
                        },
                        new
                        {
                            MaDt = "DT022",
                            HocKy = (byte)1,
                            KinhPhi = 16,
                            MaGv = 8,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty Toyota Việt Nam",
                            SoLuongToiDa = 2,
                            TenDt = "Nghiên cứu động cơ hybrid"
                        },
                        new
                        {
                            MaDt = "DT023",
                            HocKy = (byte)2,
                            KinhPhi = 5,
                            MaGv = 8,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty Thủy điện Hòa Bình",
                            SoLuongToiDa = 3,
                            TenDt = "Mô phỏng dòng chảy chất lỏng"
                        },
                        new
                        {
                            MaDt = "DT024",
                            HocKy = (byte)3,
                            KinhPhi = 8,
                            MaGv = 8,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty Cơ khí Đông Anh",
                            SoLuongToiDa = 1,
                            TenDt = "Ứng dụng in 3D trong cơ khí"
                        },
                        new
                        {
                            MaDt = "DT025",
                            HocKy = (byte)1,
                            KinhPhi = 15,
                            MaGv = 9,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty Điện mặt trời TTC",
                            SoLuongToiDa = 2,
                            TenDt = "Công nghệ năng lượng tái tạo"
                        },
                        new
                        {
                            MaDt = "DT026",
                            HocKy = (byte)2,
                            KinhPhi = 13,
                            MaGv = 9,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty Điện gió Bạc Liêu",
                            SoLuongToiDa = 3,
                            TenDt = "Ứng dụng năng lượng gió"
                        },
                        new
                        {
                            MaDt = "DT027",
                            HocKy = (byte)3,
                            KinhPhi = 19,
                            MaGv = 9,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty Pin Rạng Đông",
                            SoLuongToiDa = 1,
                            TenDt = "Nghiên cứu pin lưu trữ năng lượng"
                        },
                        new
                        {
                            MaDt = "DT028",
                            HocKy = (byte)1,
                            KinhPhi = 4,
                            MaGv = 10,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty Môi trường Bình Dương",
                            SoLuongToiDa = 2,
                            TenDt = "Xử lý chất thải rắn"
                        },
                        new
                        {
                            MaDt = "DT029",
                            HocKy = (byte)2,
                            KinhPhi = 11,
                            MaGv = 10,
                            NamHoc = (short)2025,
                            NoiThucTap = "Công ty Cấp nước Sài Gòn",
                            SoLuongToiDa = 3,
                            TenDt = "Quản lý tài nguyên nước"
                        });
                });

            modelBuilder.Entity("InternshipManagement.Models.GiangVien", b =>
                {
                    b.Property<int>("MaGv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("magv");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGv"));

                    b.Property<string>("HoTenGv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hotengv");

                    b.Property<decimal?>("Luong")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("luong");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasColumnType("char(10)")
                        .HasColumnName("makhoa");

                    b.HasKey("MaGv");

                    b.HasIndex("MaKhoa");

                    b.ToTable("GiangVien");

                    b.HasData(
                        new
                        {
                            MaGv = 1,
                            HoTenGv = "Nguyễn Thị Hoàng Khanh",
                            Luong = 22.00m,
                            MaKhoa = "CNTT"
                        },
                        new
                        {
                            MaGv = 2,
                            HoTenGv = "Trần Thị Ánh Thi",
                            Luong = 21.50m,
                            MaKhoa = "CNTT"
                        },
                        new
                        {
                            MaGv = 3,
                            HoTenGv = "Lê Văn Hùng",
                            Luong = 23.20m,
                            MaKhoa = "CNTT"
                        },
                        new
                        {
                            MaGv = 4,
                            HoTenGv = "Nguyễn Trọng Tiến",
                            Luong = 19.75m,
                            MaKhoa = "CNHH"
                        },
                        new
                        {
                            MaGv = 5,
                            HoTenGv = "Trần Nhật Hoàng Anh",
                            Luong = 18.20m,
                            MaKhoa = "CNHH"
                        },
                        new
                        {
                            MaGv = 6,
                            HoTenGv = "Phạm Hữu Phước",
                            Luong = 20.10m,
                            MaKhoa = "CNHH"
                        },
                        new
                        {
                            MaGv = 7,
                            HoTenGv = "Ngô Hữu Dũng",
                            Luong = 25.00m,
                            MaKhoa = "TCKT"
                        },
                        new
                        {
                            MaGv = 8,
                            HoTenGv = "Nguyễn Thị Hạnh",
                            Luong = 24.50m,
                            MaKhoa = "TCKT"
                        },
                        new
                        {
                            MaGv = 9,
                            HoTenGv = "Đỗ Văn Thành",
                            Luong = 22.30m,
                            MaKhoa = "TCKT"
                        },
                        new
                        {
                            MaGv = 10,
                            HoTenGv = "Tôn Long Phước",
                            Luong = 17.00m,
                            MaKhoa = "COKHI"
                        },
                        new
                        {
                            MaGv = 11,
                            HoTenGv = "Trần Thế Trung",
                            Luong = 18.50m,
                            MaKhoa = "COKHI"
                        },
                        new
                        {
                            MaGv = 12,
                            HoTenGv = "Nguyễn Văn Tài",
                            Luong = 19.20m,
                            MaKhoa = "COKHI"
                        },
                        new
                        {
                            MaGv = 13,
                            HoTenGv = "Nguyễn Văn Thắng",
                            Luong = 27.00m,
                            MaKhoa = "VCNMT"
                        },
                        new
                        {
                            MaGv = 14,
                            HoTenGv = "Võ Văn Hải",
                            Luong = 26.25m,
                            MaKhoa = "VCNMT"
                        },
                        new
                        {
                            MaGv = 15,
                            HoTenGv = "Hoàng Minh Tuấn",
                            Luong = 25.80m,
                            MaKhoa = "VCNMT"
                        },
                        new
                        {
                            MaGv = 16,
                            HoTenGv = "Nguyễn Đức Toàn",
                            Luong = 20.50m,
                            MaKhoa = "DTVT"
                        },
                        new
                        {
                            MaGv = 17,
                            HoTenGv = "Trần Văn Minh",
                            Luong = 21.00m,
                            MaKhoa = "DTVT"
                        },
                        new
                        {
                            MaGv = 18,
                            HoTenGv = "Phạm Ngọc Lâm",
                            Luong = 22.40m,
                            MaKhoa = "DTVT"
                        },
                        new
                        {
                            MaGv = 19,
                            HoTenGv = "Nguyễn Văn Hòa",
                            Luong = 23.50m,
                            MaKhoa = "DIEN"
                        },
                        new
                        {
                            MaGv = 20,
                            HoTenGv = "Phan Văn Quang",
                            Luong = 22.10m,
                            MaKhoa = "DIEN"
                        },
                        new
                        {
                            MaGv = 21,
                            HoTenGv = "Đoàn Thị Hồng",
                            Luong = 21.90m,
                            MaKhoa = "DIEN"
                        },
                        new
                        {
                            MaGv = 22,
                            HoTenGv = "Nguyễn Trọng Nhân",
                            Luong = 18.70m,
                            MaKhoa = "CKDL"
                        },
                        new
                        {
                            MaGv = 23,
                            HoTenGv = "Võ Anh Dũng",
                            Luong = 19.20m,
                            MaKhoa = "CKDL"
                        },
                        new
                        {
                            MaGv = 24,
                            HoTenGv = "Phạm Văn Hưng",
                            Luong = 20.00m,
                            MaKhoa = "CKDL"
                        },
                        new
                        {
                            MaGv = 25,
                            HoTenGv = "Nguyễn Thị Ngọc Mai",
                            Luong = 22.60m,
                            MaKhoa = "TP"
                        },
                        new
                        {
                            MaGv = 26,
                            HoTenGv = "Trần Minh Đức",
                            Luong = 23.10m,
                            MaKhoa = "TP"
                        },
                        new
                        {
                            MaGv = 27,
                            HoTenGv = "Lê Thị Thanh Tâm",
                            Luong = 21.40m,
                            MaKhoa = "TP"
                        },
                        new
                        {
                            MaGv = 28,
                            HoTenGv = "Phạm Văn Phú",
                            Luong = 24.30m,
                            MaKhoa = "XD"
                        },
                        new
                        {
                            MaGv = 29,
                            HoTenGv = "Nguyễn Văn Hạnh",
                            Luong = 23.70m,
                            MaKhoa = "XD"
                        },
                        new
                        {
                            MaGv = 30,
                            HoTenGv = "Trần Quang Vũ",
                            Luong = 22.90m,
                            MaKhoa = "XD"
                        },
                        new
                        {
                            MaGv = 31,
                            HoTenGv = "Nguyễn Thị Thu Trang",
                            Luong = 20.80m,
                            MaKhoa = "MT"
                        },
                        new
                        {
                            MaGv = 32,
                            HoTenGv = "Đỗ Minh Tuấn",
                            Luong = 21.50m,
                            MaKhoa = "MT"
                        },
                        new
                        {
                            MaGv = 33,
                            HoTenGv = "Lê Thị Phượng",
                            Luong = 22.30m,
                            MaKhoa = "MT"
                        },
                        new
                        {
                            MaGv = 34,
                            HoTenGv = "Nguyễn Thị Thanh Hòa",
                            Luong = 24.10m,
                            MaKhoa = "KT"
                        },
                        new
                        {
                            MaGv = 35,
                            HoTenGv = "Phan Văn Tùng",
                            Luong = 23.60m,
                            MaKhoa = "KT"
                        },
                        new
                        {
                            MaGv = 36,
                            HoTenGv = "Võ Thị Hồng Nhung",
                            Luong = 22.80m,
                            MaKhoa = "KT"
                        },
                        new
                        {
                            MaGv = 37,
                            HoTenGv = "Nguyễn Minh Khoa",
                            Luong = 21.70m,
                            MaKhoa = "SP"
                        },
                        new
                        {
                            MaGv = 38,
                            HoTenGv = "Trần Văn Cường",
                            Luong = 22.20m,
                            MaKhoa = "SP"
                        },
                        new
                        {
                            MaGv = 39,
                            HoTenGv = "Đinh Thị Hạnh",
                            Luong = 21.90m,
                            MaKhoa = "SP"
                        },
                        new
                        {
                            MaGv = 40,
                            HoTenGv = "Nguyễn Thị Thu Hằng",
                            Luong = 23.40m,
                            MaKhoa = "NN"
                        },
                        new
                        {
                            MaGv = 41,
                            HoTenGv = "Võ Quốc Huy",
                            Luong = 22.70m,
                            MaKhoa = "NN"
                        },
                        new
                        {
                            MaGv = 42,
                            HoTenGv = "Trần Thị Mỹ Linh",
                            Luong = 21.60m,
                            MaKhoa = "NN"
                        },
                        new
                        {
                            MaGv = 43,
                            HoTenGv = "Nguyễn Văn Khải",
                            Luong = 26.20m,
                            MaKhoa = "YDS"
                        },
                        new
                        {
                            MaGv = 44,
                            HoTenGv = "Đỗ Thị Lan",
                            Luong = 25.80m,
                            MaKhoa = "YDS"
                        },
                        new
                        {
                            MaGv = 45,
                            HoTenGv = "Lê Văn Quang",
                            Luong = 24.90m,
                            MaKhoa = "YDS"
                        },
                        new
                        {
                            MaGv = 46,
                            HoTenGv = "Phạm Thị Hồng",
                            Luong = 20.40m,
                            MaKhoa = "SH"
                        },
                        new
                        {
                            MaGv = 47,
                            HoTenGv = "Nguyễn Hữu Lộc",
                            Luong = 21.10m,
                            MaKhoa = "SH"
                        },
                        new
                        {
                            MaGv = 48,
                            HoTenGv = "Trần Thanh Bình",
                            Luong = 22.00m,
                            MaKhoa = "SH"
                        },
                        new
                        {
                            MaGv = 49,
                            HoTenGv = "Nguyễn Thị Kim Oanh",
                            Luong = 23.30m,
                            MaKhoa = "VL"
                        },
                        new
                        {
                            MaGv = 50,
                            HoTenGv = "Lê Văn Dũng",
                            Luong = 22.90m,
                            MaKhoa = "VL"
                        });
                });

            modelBuilder.Entity("InternshipManagement.Models.HuongDan", b =>
                {
                    b.Property<int>("MaSv")
                        .HasColumnType("int")
                        .HasColumnName("masv");

                    b.Property<string>("MaDt")
                        .HasColumnType("char(10)")
                        .HasColumnName("madt");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaychapnhan");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaydangky");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ghichu");

                    b.Property<decimal?>("KetQua")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("ketqua");

                    b.Property<int>("MaGv")
                        .HasColumnType("int")
                        .HasColumnName("magv");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint")
                        .HasColumnName("trangthai");

                    b.HasKey("MaSv", "MaDt");

                    b.HasIndex("MaGv");

                    b.HasIndex("MaDt", "TrangThai");

                    b.ToTable("HuongDan");

                    b.HasData(
                        new
                        {
                            MaSv = 1001,
                            MaDt = "DT001",
                            AcceptedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Đã duyệt tham gia",
                            MaGv = 1,
                            TrangThai = (byte)1
                        },
                        new
                        {
                            MaSv = 1002,
                            MaDt = "DT002",
                            CreatedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Đang chờ giảng viên duyệt",
                            MaGv = 1,
                            TrangThai = (byte)0
                        },
                        new
                        {
                            MaSv = 1003,
                            MaDt = "DT004",
                            AcceptedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Đang thực hiện đề tài IoT",
                            MaGv = 2,
                            TrangThai = (byte)2
                        },
                        new
                        {
                            MaSv = 1004,
                            MaDt = "DT005",
                            AcceptedAt = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Đã hoàn thành xuất sắc",
                            KetQua = 8.5m,
                            MaGv = 2,
                            TrangThai = (byte)3
                        },
                        new
                        {
                            MaSv = 1005,
                            MaDt = "DT007",
                            AcceptedAt = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Được phân công đề tài Vật liệu mới",
                            MaGv = 3,
                            TrangThai = (byte)1
                        },
                        new
                        {
                            MaSv = 1006,
                            MaDt = "DT008",
                            CreatedAt = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Đề tài không phù hợp",
                            MaGv = 3,
                            TrangThai = (byte)4
                        },
                        new
                        {
                            MaSv = 1007,
                            MaDt = "DT010",
                            AcceptedAt = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Sinh viên xin rút",
                            MaGv = 4,
                            TrangThai = (byte)5
                        },
                        new
                        {
                            MaSv = 1008,
                            MaDt = "DT013",
                            CreatedAt = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Đang chờ xác nhận",
                            MaGv = 5,
                            TrangThai = (byte)0
                        },
                        new
                        {
                            MaSv = 1009,
                            MaDt = "DT003",
                            AcceptedAt = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Sinh viên đã bắt đầu làm việc",
                            MaGv = 1,
                            TrangThai = (byte)2
                        },
                        new
                        {
                            MaSv = 1010,
                            MaDt = "DT009",
                            AcceptedAt = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Bảo vệ thành công",
                            KetQua = 9.0m,
                            MaGv = 3,
                            TrangThai = (byte)3
                        },
                        new
                        {
                            MaSv = 1011,
                            MaDt = "DT013",
                            CreatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Đang chờ xét duyệt",
                            MaGv = 5,
                            TrangThai = (byte)0
                        },
                        new
                        {
                            MaSv = 1012,
                            MaDt = "DT014",
                            AcceptedAt = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Được chấp nhận vào nhóm",
                            MaGv = 5,
                            TrangThai = (byte)1
                        },
                        new
                        {
                            MaSv = 1013,
                            MaDt = "DT015",
                            AcceptedAt = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Đang thu thập số liệu",
                            MaGv = 5,
                            TrangThai = (byte)2
                        },
                        new
                        {
                            MaSv = 1014,
                            MaDt = "DT016",
                            AcceptedAt = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Hoàn thành tốt",
                            KetQua = 8.0m,
                            MaGv = 6,
                            TrangThai = (byte)3
                        },
                        new
                        {
                            MaSv = 1015,
                            MaDt = "DT017",
                            CreatedAt = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Đang chờ duyệt",
                            MaGv = 6,
                            TrangThai = (byte)0
                        },
                        new
                        {
                            MaSv = 1016,
                            MaDt = "DT018",
                            AcceptedAt = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Chuẩn bị triển khai",
                            MaGv = 6,
                            TrangThai = (byte)1
                        },
                        new
                        {
                            MaSv = 1017,
                            MaDt = "DT019",
                            AcceptedAt = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Đang thiết kế mô hình",
                            MaGv = 7,
                            TrangThai = (byte)2
                        },
                        new
                        {
                            MaSv = 1018,
                            MaDt = "DT020",
                            AcceptedAt = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Đã nộp báo cáo",
                            KetQua = 7.5m,
                            MaGv = 7,
                            TrangThai = (byte)3
                        },
                        new
                        {
                            MaSv = 1019,
                            MaDt = "DT021",
                            CreatedAt = new DateTime(2025, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Đăng ký mới",
                            MaGv = 7,
                            TrangThai = (byte)0
                        },
                        new
                        {
                            MaSv = 1020,
                            MaDt = "DT022",
                            AcceptedAt = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Được phân công thực hiện",
                            MaGv = 8,
                            TrangThai = (byte)1
                        },
                        new
                        {
                            MaSv = 1021,
                            MaDt = "DT023",
                            AcceptedAt = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Đang phân tích dữ liệu",
                            MaGv = 8,
                            TrangThai = (byte)2
                        },
                        new
                        {
                            MaSv = 1022,
                            MaDt = "DT024",
                            AcceptedAt = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Xuất sắc",
                            KetQua = 9.2m,
                            MaGv = 8,
                            TrangThai = (byte)3
                        },
                        new
                        {
                            MaSv = 1023,
                            MaDt = "DT025",
                            CreatedAt = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Đang chờ xác nhận",
                            MaGv = 9,
                            TrangThai = (byte)0
                        },
                        new
                        {
                            MaSv = 1024,
                            MaDt = "DT026",
                            AcceptedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "GV đồng ý cho tham gia",
                            MaGv = 9,
                            TrangThai = (byte)1
                        },
                        new
                        {
                            MaSv = 1025,
                            MaDt = "DT027",
                            AcceptedAt = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Đang làm báo cáo giữa kỳ",
                            MaGv = 9,
                            TrangThai = (byte)2
                        },
                        new
                        {
                            MaSv = 1026,
                            MaDt = "DT028",
                            AcceptedAt = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Hoàn tất bảo vệ",
                            KetQua = 8.7m,
                            MaGv = 10,
                            TrangThai = (byte)3
                        },
                        new
                        {
                            MaSv = 1027,
                            MaDt = "DT029",
                            CreatedAt = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Đăng ký mới",
                            MaGv = 10,
                            TrangThai = (byte)0
                        },
                        new
                        {
                            MaSv = 1028,
                            MaDt = "DT011",
                            AcceptedAt = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Chuyển đề tài phù hợp",
                            MaGv = 4,
                            TrangThai = (byte)1
                        },
                        new
                        {
                            MaSv = 1029,
                            MaDt = "DT012",
                            AcceptedAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Đang triển khai thí nghiệm",
                            MaGv = 4,
                            TrangThai = (byte)2
                        },
                        new
                        {
                            MaSv = 1030,
                            MaDt = "DT015",
                            AcceptedAt = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GhiChu = "Hoàn thành xuất sắc",
                            KetQua = 9.5m,
                            MaGv = 5,
                            TrangThai = (byte)3
                        });
                });

            modelBuilder.Entity("InternshipManagement.Models.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .HasColumnName("makhoa");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dienthoai");

                    b.Property<string>("TenKhoa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenkhoa");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoa");

                    b.HasData(
                        new
                        {
                            MaKhoa = "CNTT",
                            DienThoai = "0901234567",
                            TenKhoa = "Khoa Công nghệ Thông tin"
                        },
                        new
                        {
                            MaKhoa = "CNHH",
                            DienThoai = "0901234572",
                            TenKhoa = "Khoa Công nghệ Hóa học"
                        },
                        new
                        {
                            MaKhoa = "TCKT",
                            DienThoai = "0901234576",
                            TenKhoa = "Khoa Tài chính - Kế toán"
                        },
                        new
                        {
                            MaKhoa = "COKHI",
                            DienThoai = "0901234570",
                            TenKhoa = "Khoa Cơ khí"
                        },
                        new
                        {
                            MaKhoa = "VCNMT",
                            DienThoai = "0901234582",
                            TenKhoa = "Viện Công nghệ & Môi trường"
                        },
                        new
                        {
                            MaKhoa = "DTVT",
                            DienThoai = "0901234568",
                            TenKhoa = "Khoa Điện tử - Viễn thông"
                        },
                        new
                        {
                            MaKhoa = "DIEN",
                            DienThoai = "0901234569",
                            TenKhoa = "Khoa Điện - Điện tử"
                        },
                        new
                        {
                            MaKhoa = "CKDL",
                            DienThoai = "0901234571",
                            TenKhoa = "Khoa Cơ khí Động lực"
                        },
                        new
                        {
                            MaKhoa = "TP",
                            DienThoai = "0901234573",
                            TenKhoa = "Khoa Công nghệ Thực phẩm"
                        },
                        new
                        {
                            MaKhoa = "XD",
                            DienThoai = "0901234574",
                            TenKhoa = "Khoa Xây dựng"
                        },
                        new
                        {
                            MaKhoa = "MT",
                            DienThoai = "0901234575",
                            TenKhoa = "Khoa Môi trường"
                        },
                        new
                        {
                            MaKhoa = "KT",
                            DienThoai = "0901234576",
                            TenKhoa = "Khoa Kinh tế"
                        },
                        new
                        {
                            MaKhoa = "SP",
                            DienThoai = "0901234577",
                            TenKhoa = "Khoa Sư phạm Kỹ thuật"
                        },
                        new
                        {
                            MaKhoa = "NN",
                            DienThoai = "0901234578",
                            TenKhoa = "Khoa Ngoại ngữ"
                        },
                        new
                        {
                            MaKhoa = "YDS",
                            DienThoai = "0901234579",
                            TenKhoa = "Khoa Y Dược"
                        },
                        new
                        {
                            MaKhoa = "SH",
                            DienThoai = "0901234580",
                            TenKhoa = "Khoa Sinh học - CNSH"
                        },
                        new
                        {
                            MaKhoa = "VL",
                            DienThoai = "0901234581",
                            TenKhoa = "Khoa Vật liệu"
                        });
                });

            modelBuilder.Entity("InternshipManagement.Models.SinhVien", b =>
                {
                    b.Property<int>("MaSv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("masv");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSv"));

                    b.Property<string>("HoTenSv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hotensv");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .HasColumnName("makhoa");

                    b.Property<int?>("NamSinh")
                        .HasColumnType("int")
                        .HasColumnName("namsinh");

                    b.Property<string>("QueQuan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("quequan");

                    b.HasKey("MaSv");

                    b.HasIndex("MaKhoa");

                    b.ToTable("SinhVien");

                    b.HasData(
                        new
                        {
                            MaSv = 1001,
                            HoTenSv = "Nguyễn Văn An",
                            MaKhoa = "CNTT",
                            NamSinh = 2002,
                            QueQuan = "Hà Nội"
                        },
                        new
                        {
                            MaSv = 1002,
                            HoTenSv = "Trần Thị Bình",
                            MaKhoa = "CNTT",
                            NamSinh = 2003,
                            QueQuan = "Hải Phòng"
                        },
                        new
                        {
                            MaSv = 1003,
                            HoTenSv = "Phạm Đức Chiến",
                            MaKhoa = "CNTT",
                            NamSinh = 2001,
                            QueQuan = "Nam Định"
                        },
                        new
                        {
                            MaSv = 1004,
                            HoTenSv = "Lê Minh Châu",
                            MaKhoa = "CNTT",
                            NamSinh = 2002,
                            QueQuan = "Thái Bình"
                        },
                        new
                        {
                            MaSv = 1005,
                            HoTenSv = "Vũ Ngọc Diệp",
                            MaKhoa = "CNTT",
                            NamSinh = 2004,
                            QueQuan = "Hà Nam"
                        },
                        new
                        {
                            MaSv = 1006,
                            HoTenSv = "Đỗ Thanh Dương",
                            MaKhoa = "CNHH",
                            NamSinh = 2002,
                            QueQuan = "Nghệ An"
                        },
                        new
                        {
                            MaSv = 1007,
                            HoTenSv = "Ngô Thị Giang",
                            MaKhoa = "CNHH",
                            NamSinh = 2003,
                            QueQuan = "Thanh Hóa"
                        },
                        new
                        {
                            MaSv = 1008,
                            HoTenSv = "Bùi Mạnh Hà",
                            MaKhoa = "CNHH",
                            NamSinh = 2001,
                            QueQuan = "Hà Tĩnh"
                        },
                        new
                        {
                            MaSv = 1009,
                            HoTenSv = "Hoàng Thu Hằng",
                            MaKhoa = "CNHH",
                            NamSinh = 2002,
                            QueQuan = "Quảng Bình"
                        },
                        new
                        {
                            MaSv = 1010,
                            HoTenSv = "Phan Việt Hoàng",
                            MaKhoa = "CNHH",
                            NamSinh = 2004,
                            QueQuan = "Quảng Trị"
                        },
                        new
                        {
                            MaSv = 1011,
                            HoTenSv = "Đặng Minh Huy",
                            MaKhoa = "TCKT",
                            NamSinh = 2002,
                            QueQuan = "Huế"
                        },
                        new
                        {
                            MaSv = 1012,
                            HoTenSv = "Trịnh Khánh Linh",
                            MaKhoa = "TCKT",
                            NamSinh = 2001,
                            QueQuan = "Đà Nẵng"
                        },
                        new
                        {
                            MaSv = 1013,
                            HoTenSv = "Mai Nhật Long",
                            MaKhoa = "TCKT",
                            NamSinh = 2003,
                            QueQuan = "Quảng Nam"
                        },
                        new
                        {
                            MaSv = 1014,
                            HoTenSv = "Tô Hồng Nhung",
                            MaKhoa = "TCKT",
                            NamSinh = 2002,
                            QueQuan = "Quảng Ngãi"
                        },
                        new
                        {
                            MaSv = 1015,
                            HoTenSv = "Phùng Quang Nam",
                            MaKhoa = "TCKT",
                            NamSinh = 2004,
                            QueQuan = "Bình Định"
                        },
                        new
                        {
                            MaSv = 1016,
                            HoTenSv = "Nguyễn Văn Phúc",
                            MaKhoa = "COKHI",
                            NamSinh = 2002,
                            QueQuan = "Khánh Hòa"
                        },
                        new
                        {
                            MaSv = 1017,
                            HoTenSv = "Trần Thanh Phương",
                            MaKhoa = "COKHI",
                            NamSinh = 2003,
                            QueQuan = "Ninh Thuận"
                        },
                        new
                        {
                            MaSv = 1018,
                            HoTenSv = "Lê Hoài Phong",
                            MaKhoa = "COKHI",
                            NamSinh = 2001,
                            QueQuan = "Bình Thuận"
                        },
                        new
                        {
                            MaSv = 1019,
                            HoTenSv = "Võ Thị Quỳnh",
                            MaKhoa = "COKHI",
                            NamSinh = 2002,
                            QueQuan = "Gia Lai"
                        },
                        new
                        {
                            MaSv = 1020,
                            HoTenSv = "Phạm Công Sơn",
                            MaKhoa = "COKHI",
                            NamSinh = 2004,
                            QueQuan = "Đắk Lắk"
                        },
                        new
                        {
                            MaSv = 1021,
                            HoTenSv = "Đỗ Thị Thu",
                            MaKhoa = "VCNMT",
                            NamSinh = 2001,
                            QueQuan = "Lâm Đồng"
                        },
                        new
                        {
                            MaSv = 1022,
                            HoTenSv = "Ngô Bảo Trâm",
                            MaKhoa = "VCNMT",
                            NamSinh = 2002,
                            QueQuan = "Bình Dương"
                        },
                        new
                        {
                            MaSv = 1023,
                            HoTenSv = "Hoàng Gia Tuấn",
                            MaKhoa = "VCNMT",
                            NamSinh = 2003,
                            QueQuan = "Đồng Nai"
                        },
                        new
                        {
                            MaSv = 1024,
                            HoTenSv = "Phan Thị Uyên",
                            MaKhoa = "VCNMT",
                            NamSinh = 2002,
                            QueQuan = "Tây Ninh"
                        },
                        new
                        {
                            MaSv = 1025,
                            HoTenSv = "Bùi Minh Vũ",
                            MaKhoa = "VCNMT",
                            NamSinh = 2004,
                            QueQuan = "TP. Hồ Chí Minh"
                        },
                        new
                        {
                            MaSv = 1026,
                            HoTenSv = "Trần Anh Vy",
                            MaKhoa = "CNTT",
                            NamSinh = 2001,
                            QueQuan = "Cần Thơ"
                        },
                        new
                        {
                            MaSv = 1027,
                            HoTenSv = "Nguyễn Hải Yến",
                            MaKhoa = "TCKT",
                            NamSinh = 2002,
                            QueQuan = "An Giang"
                        },
                        new
                        {
                            MaSv = 1028,
                            HoTenSv = "Phạm Đức Anh",
                            MaKhoa = "CNHH",
                            NamSinh = 2003,
                            QueQuan = "Kiên Giang"
                        },
                        new
                        {
                            MaSv = 1029,
                            HoTenSv = "Lê Thị Bảo Châu",
                            MaKhoa = "COKHI",
                            NamSinh = 2001,
                            QueQuan = "Vĩnh Long"
                        },
                        new
                        {
                            MaSv = 1030,
                            HoTenSv = "Võ Minh Duy",
                            MaKhoa = "VCNMT",
                            NamSinh = 2002,
                            QueQuan = "Bến Tre"
                        });
                });

            modelBuilder.Entity("InternshipManagement.Models.DeTai", b =>
                {
                    b.HasOne("InternshipManagement.Models.GiangVien", "GiangVien")
                        .WithMany("DeTais")
                        .HasForeignKey("MaGv")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("InternshipManagement.Models.GiangVien", b =>
                {
                    b.HasOne("InternshipManagement.Models.Khoa", "Khoa")
                        .WithMany("GiangViens")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("InternshipManagement.Models.HuongDan", b =>
                {
                    b.HasOne("InternshipManagement.Models.DeTai", "DeTai")
                        .WithMany("HuongDans")
                        .HasForeignKey("MaDt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternshipManagement.Models.GiangVien", "GiangVien")
                        .WithMany("HuongDans")
                        .HasForeignKey("MaGv")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternshipManagement.Models.SinhVien", "SinhVien")
                        .WithMany("HuongDans")
                        .HasForeignKey("MaSv")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeTai");

                    b.Navigation("GiangVien");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("InternshipManagement.Models.SinhVien", b =>
                {
                    b.HasOne("InternshipManagement.Models.Khoa", "Khoa")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("InternshipManagement.Models.DeTai", b =>
                {
                    b.Navigation("HuongDans");
                });

            modelBuilder.Entity("InternshipManagement.Models.GiangVien", b =>
                {
                    b.Navigation("DeTais");

                    b.Navigation("HuongDans");
                });

            modelBuilder.Entity("InternshipManagement.Models.Khoa", b =>
                {
                    b.Navigation("GiangViens");

                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("InternshipManagement.Models.SinhVien", b =>
                {
                    b.Navigation("HuongDans");
                });
#pragma warning restore 612, 618
        }
    }
}
