// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternshipManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternshipManagement.Models.AppUser", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("passwordhash");

                    b.HasKey("Code", "Role");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("InternshipManagement.Models.DeTai", b =>
                {
                    b.Property<string>("MaDt")
                        .HasColumnType("char(10)")
                        .HasColumnName("madt");

                    b.Property<int?>("KinhPhi")
                        .HasColumnType("int")
                        .HasColumnName("kinhphi");

                    b.Property<string>("NoiThucTap")
                        .HasColumnType("char(30)")
                        .HasColumnName("NoiThucTap");

                    b.Property<string>("TenDt")
                        .HasColumnType("char(30)")
                        .HasColumnName("tendt");

                    b.HasKey("MaDt");

                    b.ToTable("DeTai");

                    b.HasData(
                        new
                        {
                            MaDt = "DT01",
                            KinhPhi = 8000,
                            NoiThucTap = "FPT Software",
                            TenDt = "Website ban sach"
                        },
                        new
                        {
                            MaDt = "DT02",
                            KinhPhi = 9000,
                            NoiThucTap = "VNPT",
                            TenDt = "Quan ly phong gym"
                        },
                        new
                        {
                            MaDt = "DT03",
                            KinhPhi = 12000,
                            NoiThucTap = "Viettel",
                            TenDt = "Phan tich du lieu ban hang"
                        },
                        new
                        {
                            MaDt = "DT04",
                            KinhPhi = 15000,
                            NoiThucTap = "Vedan",
                            TenDt = "Toi uu quy trinh pha che"
                        },
                        new
                        {
                            MaDt = "DT05",
                            KinhPhi = 11000,
                            NoiThucTap = "PVN",
                            TenDt = "Thiet ke phan ung hoa hoc"
                        },
                        new
                        {
                            MaDt = "DT06",
                            KinhPhi = 7000,
                            NoiThucTap = "KPMG",
                            TenDt = "Ke toan quan tri chi phi"
                        },
                        new
                        {
                            MaDt = "DT07",
                            KinhPhi = 6000,
                            NoiThucTap = "PwC",
                            TenDt = "Phan tich bao cao tai chinh"
                        },
                        new
                        {
                            MaDt = "DT08",
                            KinhPhi = 14000,
                            NoiThucTap = "Thaco",
                            TenDt = "Thiet ke khuon dap co khi"
                        },
                        new
                        {
                            MaDt = "DT09",
                            KinhPhi = 16000,
                            NoiThucTap = "VinFast",
                            TenDt = "Mo phong co cau robot"
                        },
                        new
                        {
                            MaDt = "DT10",
                            KinhPhi = 10000,
                            NoiThucTap = "CETASD",
                            TenDt = "Quan trac moi truong nuoc"
                        },
                        new
                        {
                            MaDt = "DT11",
                            KinhPhi = 18000,
                            NoiThucTap = "TMA",
                            TenDt = "Ung dung IoT trong nong nghiep"
                        },
                        new
                        {
                            MaDt = "DT12",
                            KinhPhi = 9000,
                            NoiThucTap = "Co.op",
                            TenDt = "Phan tich chuoi cung ung"
                        },
                        new
                        {
                            MaDt = "DT13",
                            KinhPhi = 13000,
                            NoiThucTap = "Misa",
                            TenDt = "He thong ERP mini"
                        },
                        new
                        {
                            MaDt = "DT14",
                            KinhPhi = 20000,
                            NoiThucTap = "Bosch",
                            TenDt = "Xu ly anh cong nghiep"
                        },
                        new
                        {
                            MaDt = "DT15",
                            KinhPhi = 17000,
                            NoiThucTap = "Lilama",
                            TenDt = "Thiet ke he thong thuy luc"
                        },
                        new
                        {
                            MaDt = "DT16",
                            KinhPhi = 8000,
                            NoiThucTap = "VWS",
                            TenDt = "Danh gia rui ro moi truong"
                        },
                        new
                        {
                            MaDt = "DT17",
                            KinhPhi = 11000,
                            NoiThucTap = "Sabeco",
                            TenDt = "Quan ly kho thong minh"
                        },
                        new
                        {
                            MaDt = "DT18",
                            KinhPhi = 10000,
                            NoiThucTap = "FPT Software",
                            TenDt = "Chatbot ho tro sinh vien"
                        },
                        new
                        {
                            MaDt = "DT19",
                            KinhPhi = 15000,
                            NoiThucTap = "CMC",
                            TenDt = "Xay dung he thong CRM"
                        },
                        new
                        {
                            MaDt = "DT20",
                            KinhPhi = 9000,
                            NoiThucTap = "Dabaco",
                            TenDt = "Toi uu cong thuc tron"
                        },
                        new
                        {
                            MaDt = "DT21",
                            KinhPhi = 5000,
                            NoiThucTap = "Deloitte",
                            TenDt = "Ke toan tien luong"
                        },
                        new
                        {
                            MaDt = "DT22",
                            KinhPhi = 7000,
                            NoiThucTap = "EY",
                            TenDt = "Phan tich thue va kiem toan"
                        },
                        new
                        {
                            MaDt = "DT23",
                            KinhPhi = 12000,
                            NoiThucTap = "Hoa Phat",
                            TenDt = "Thiet ke bang tai"
                        },
                        new
                        {
                            MaDt = "DT24",
                            KinhPhi = 18000,
                            NoiThucTap = "Datalogic",
                            TenDt = "Gia cong CNC 5 truc"
                        },
                        new
                        {
                            MaDt = "DT25",
                            KinhPhi = 16000,
                            NoiThucTap = "BIWASE",
                            TenDt = "Xu ly nuoc thai do thi"
                        },
                        new
                        {
                            MaDt = "DT26",
                            KinhPhi = 14000,
                            NoiThucTap = "ENVI",
                            TenDt = "Giam sat chat luong khong khi"
                        },
                        new
                        {
                            MaDt = "DT27",
                            KinhPhi = 10000,
                            NoiThucTap = "GHN",
                            TenDt = "Hau can thuong mai dien tu"
                        },
                        new
                        {
                            MaDt = "DT28",
                            KinhPhi = 13000,
                            NoiThucTap = "VinComm",
                            TenDt = "Du bao nhu cau ban le"
                        },
                        new
                        {
                            MaDt = "DT29",
                            KinhPhi = 20000,
                            NoiThucTap = "VNG",
                            TenDt = "Hoc sau phat hien bat thuong"
                        },
                        new
                        {
                            MaDt = "DT30",
                            KinhPhi = 19000,
                            NoiThucTap = "SolarBK",
                            TenDt = "Nang luong tai tao san xuat"
                        });
                });

            modelBuilder.Entity("InternshipManagement.Models.GiangVien", b =>
                {
                    b.Property<int>("MaGv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("magv");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGv"));

                    b.Property<string>("HoTenGv")
                        .HasColumnType("char(30)")
                        .HasColumnName("hotengv");

                    b.Property<decimal?>("Luong")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("luong");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasColumnType("char(10)")
                        .HasColumnName("makhoa");

                    b.HasKey("MaGv");

                    b.HasIndex("MaKhoa");

                    b.ToTable("GiangVien");

                    b.HasData(
                        new
                        {
                            MaGv = 1,
                            HoTenGv = "Nguyen Thi Hoang Khanh",
                            Luong = 22.00m,
                            MaKhoa = "CNTT"
                        },
                        new
                        {
                            MaGv = 2,
                            HoTenGv = "Tran Thi Anh Thi",
                            Luong = 21.50m,
                            MaKhoa = "CNTT"
                        },
                        new
                        {
                            MaGv = 3,
                            HoTenGv = "Nguyen Trong Tien",
                            Luong = 19.75m,
                            MaKhoa = "CNHH"
                        },
                        new
                        {
                            MaGv = 4,
                            HoTenGv = "Tran Nhat Hoang Anh",
                            Luong = 18.20m,
                            MaKhoa = "CNHH"
                        },
                        new
                        {
                            MaGv = 5,
                            HoTenGv = "Ngo Huu Dung",
                            Luong = 25.00m,
                            MaKhoa = "TCKT"
                        },
                        new
                        {
                            MaGv = 6,
                            HoTenGv = "Nguyen Thi Hanh",
                            Luong = 24.50m,
                            MaKhoa = "TCKT"
                        },
                        new
                        {
                            MaGv = 7,
                            HoTenGv = "Ton Long Phuoc",
                            Luong = 17.00m,
                            MaKhoa = "COKHI"
                        },
                        new
                        {
                            MaGv = 8,
                            HoTenGv = "Tran The Trung",
                            Luong = 18.50m,
                            MaKhoa = "COKHI"
                        },
                        new
                        {
                            MaGv = 9,
                            HoTenGv = "Nguyen Van Thang",
                            Luong = 27.00m,
                            MaKhoa = "VCNMT"
                        },
                        new
                        {
                            MaGv = 10,
                            HoTenGv = "Vo Van Hai",
                            Luong = 26.25m,
                            MaKhoa = "VCNMT"
                        });
                });

            modelBuilder.Entity("InternshipManagement.Models.HuongDan", b =>
                {
                    b.Property<int>("MaSv")
                        .HasColumnType("int")
                        .HasColumnName("masv");

                    b.Property<string>("MaDt")
                        .HasColumnType("char(10)")
                        .HasColumnName("madt");

                    b.Property<int>("MaGv")
                        .HasColumnType("int")
                        .HasColumnName("magv");

                    b.Property<decimal?>("KetQua")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("ketqua");

                    b.HasKey("MaSv", "MaDt", "MaGv");

                    b.HasIndex("MaDt");

                    b.HasIndex("MaGv");

                    b.ToTable("HuongDan");

                    b.HasData(
                        new
                        {
                            MaSv = 1001,
                            MaDt = "DT01",
                            MaGv = 1,
                            KetQua = 8.50m
                        },
                        new
                        {
                            MaSv = 1002,
                            MaDt = "DT02",
                            MaGv = 2,
                            KetQua = 8.00m
                        },
                        new
                        {
                            MaSv = 1003,
                            MaDt = "DT03",
                            MaGv = 1,
                            KetQua = 8.70m
                        },
                        new
                        {
                            MaSv = 1004,
                            MaDt = "DT11",
                            MaGv = 2,
                            KetQua = 9.00m
                        },
                        new
                        {
                            MaSv = 1005,
                            MaDt = "DT18",
                            MaGv = 1,
                            KetQua = 8.90m
                        },
                        new
                        {
                            MaSv = 1006,
                            MaDt = "DT04",
                            MaGv = 3,
                            KetQua = 8.10m
                        },
                        new
                        {
                            MaSv = 1007,
                            MaDt = "DT05",
                            MaGv = 4,
                            KetQua = 7.80m
                        },
                        new
                        {
                            MaSv = 1008,
                            MaDt = "DT20",
                            MaGv = 3,
                            KetQua = 8.40m
                        },
                        new
                        {
                            MaSv = 1009,
                            MaDt = "DT26",
                            MaGv = 4,
                            KetQua = 8.60m
                        },
                        new
                        {
                            MaSv = 1010,
                            MaDt = "DT16",
                            MaGv = 3,
                            KetQua = 8.20m
                        },
                        new
                        {
                            MaSv = 1011,
                            MaDt = "DT06",
                            MaGv = 5,
                            KetQua = 8.00m
                        },
                        new
                        {
                            MaSv = 1012,
                            MaDt = "DT07",
                            MaGv = 6,
                            KetQua = 8.30m
                        },
                        new
                        {
                            MaSv = 1013,
                            MaDt = "DT12",
                            MaGv = 6,
                            KetQua = 7.90m
                        },
                        new
                        {
                            MaSv = 1014,
                            MaDt = "DT21",
                            MaGv = 5,
                            KetQua = 8.40m
                        },
                        new
                        {
                            MaSv = 1015,
                            MaDt = "DT22",
                            MaGv = 6,
                            KetQua = 8.10m
                        },
                        new
                        {
                            MaSv = 1016,
                            MaDt = "DT08",
                            MaGv = 7,
                            KetQua = 8.20m
                        },
                        new
                        {
                            MaSv = 1017,
                            MaDt = "DT09",
                            MaGv = 8,
                            KetQua = 8.60m
                        },
                        new
                        {
                            MaSv = 1018,
                            MaDt = "DT15",
                            MaGv = 7,
                            KetQua = 8.30m
                        },
                        new
                        {
                            MaSv = 1019,
                            MaDt = "DT23",
                            MaGv = 8,
                            KetQua = 7.70m
                        },
                        new
                        {
                            MaSv = 1020,
                            MaDt = "DT24",
                            MaGv = 7,
                            KetQua = 8.00m
                        },
                        new
                        {
                            MaSv = 1021,
                            MaDt = "DT10",
                            MaGv = 9,
                            KetQua = 8.50m
                        },
                        new
                        {
                            MaSv = 1022,
                            MaDt = "DT16",
                            MaGv = 10,
                            KetQua = 8.20m
                        },
                        new
                        {
                            MaSv = 1023,
                            MaDt = "DT25",
                            MaGv = 9,
                            KetQua = 8.60m
                        },
                        new
                        {
                            MaSv = 1024,
                            MaDt = "DT26",
                            MaGv = 10,
                            KetQua = 8.40m
                        },
                        new
                        {
                            MaSv = 1025,
                            MaDt = "DT30",
                            MaGv = 9,
                            KetQua = 8.80m
                        },
                        new
                        {
                            MaSv = 1026,
                            MaDt = "DT19",
                            MaGv = 2,
                            KetQua = 8.70m
                        },
                        new
                        {
                            MaSv = 1027,
                            MaDt = "DT12",
                            MaGv = 6,
                            KetQua = 8.10m
                        },
                        new
                        {
                            MaSv = 1028,
                            MaDt = "DT05",
                            MaGv = 3,
                            KetQua = 8.00m
                        },
                        new
                        {
                            MaSv = 1029,
                            MaDt = "DT23",
                            MaGv = 8,
                            KetQua = 7.80m
                        },
                        new
                        {
                            MaSv = 1030,
                            MaDt = "DT25",
                            MaGv = 9,
                            KetQua = 8.60m
                        });
                });

            modelBuilder.Entity("InternshipManagement.Models.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasColumnType("char(10)")
                        .HasColumnName("makhoa");

                    b.Property<string>("DienThoai")
                        .HasColumnType("char(10)")
                        .HasColumnName("dienthoai");

                    b.Property<string>("TenKhoa")
                        .HasColumnType("char(30)")
                        .HasColumnName("tenkhoa");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoa");

                    b.HasData(
                        new
                        {
                            MaKhoa = "CNTT",
                            DienThoai = "0901234567",
                            TenKhoa = "Cong nghe thong tin"
                        },
                        new
                        {
                            MaKhoa = "CNHH",
                            DienThoai = "0902345678",
                            TenKhoa = "Cong nghe hoa hoc"
                        },
                        new
                        {
                            MaKhoa = "TCKT",
                            DienThoai = "0903456789",
                            TenKhoa = "Tai chinh - Ke toan"
                        },
                        new
                        {
                            MaKhoa = "COKHI",
                            DienThoai = "0904567890",
                            TenKhoa = "Co khi"
                        },
                        new
                        {
                            MaKhoa = "VCNMT",
                            DienThoai = "0905678901",
                            TenKhoa = "Vien cong nghe va moi truong"
                        });
                });

            modelBuilder.Entity("InternshipManagement.Models.SinhVien", b =>
                {
                    b.Property<int>("MaSv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("masv");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSv"));

                    b.Property<string>("HoTenSv")
                        .HasColumnType("char(30)")
                        .HasColumnName("hotensv");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasColumnType("char(10)")
                        .HasColumnName("makhoa");

                    b.Property<int?>("NamSinh")
                        .HasColumnType("int")
                        .HasColumnName("namsinh");

                    b.Property<string>("QueQuan")
                        .HasColumnType("char(30)")
                        .HasColumnName("quequan");

                    b.HasKey("MaSv");

                    b.HasIndex("MaKhoa");

                    b.ToTable("SinhVien");

                    b.HasData(
                        new
                        {
                            MaSv = 1001,
                            HoTenSv = "Nguyenk Van An",
                            MaKhoa = "CNTT",
                            NamSinh = 2002,
                            QueQuan = "Ha Noi"
                        },
                        new
                        {
                            MaSv = 1002,
                            HoTenSv = "Tran Thi Binh",
                            MaKhoa = "CNTT",
                            NamSinh = 2003,
                            QueQuan = "Hai Phong"
                        },
                        new
                        {
                            MaSv = 1003,
                            HoTenSv = "Pham Duc Chien",
                            MaKhoa = "CNTT",
                            NamSinh = 2001,
                            QueQuan = "Nam Dinh"
                        },
                        new
                        {
                            MaSv = 1004,
                            HoTenSv = "Le Minh Chau",
                            MaKhoa = "CNTT",
                            NamSinh = 2002,
                            QueQuan = "Thai Binh"
                        },
                        new
                        {
                            MaSv = 1005,
                            HoTenSv = "Vu Ngoc Diep",
                            MaKhoa = "CNTT",
                            NamSinh = 2004,
                            QueQuan = "Ha Nam"
                        },
                        new
                        {
                            MaSv = 1006,
                            HoTenSv = "Do Thanh Duong",
                            MaKhoa = "CNHH",
                            NamSinh = 2002,
                            QueQuan = "Nghe An"
                        },
                        new
                        {
                            MaSv = 1007,
                            HoTenSv = "Ngo Thi Giang",
                            MaKhoa = "CNHH",
                            NamSinh = 2003,
                            QueQuan = "Thanh Hoa"
                        },
                        new
                        {
                            MaSv = 1008,
                            HoTenSv = "Bui Manh Ha",
                            MaKhoa = "CNHH",
                            NamSinh = 2001,
                            QueQuan = "Ha Tinh"
                        },
                        new
                        {
                            MaSv = 1009,
                            HoTenSv = "Hoang Thu Hang",
                            MaKhoa = "CNHH",
                            NamSinh = 2002,
                            QueQuan = "Quang Binh"
                        },
                        new
                        {
                            MaSv = 1010,
                            HoTenSv = "Phan Viet Hoang",
                            MaKhoa = "CNHH",
                            NamSinh = 2004,
                            QueQuan = "Quang Tri"
                        },
                        new
                        {
                            MaSv = 1011,
                            HoTenSv = "Dang Minh Huy",
                            MaKhoa = "TCKT",
                            NamSinh = 2002,
                            QueQuan = "Hue"
                        },
                        new
                        {
                            MaSv = 1012,
                            HoTenSv = "Trinh Khanh Linh",
                            MaKhoa = "TCKT",
                            NamSinh = 2001,
                            QueQuan = "Da Nang"
                        },
                        new
                        {
                            MaSv = 1013,
                            HoTenSv = "Mai Nhat Long",
                            MaKhoa = "TCKT",
                            NamSinh = 2003,
                            QueQuan = "Quang Nam"
                        },
                        new
                        {
                            MaSv = 1014,
                            HoTenSv = "To Hong Nhung",
                            MaKhoa = "TCKT",
                            NamSinh = 2002,
                            QueQuan = "Quang Ngai"
                        },
                        new
                        {
                            MaSv = 1015,
                            HoTenSv = "Phung Quang Nam",
                            MaKhoa = "TCKT",
                            NamSinh = 2004,
                            QueQuan = "Binh Dinh"
                        },
                        new
                        {
                            MaSv = 1016,
                            HoTenSv = "Nguyen Van Phuc",
                            MaKhoa = "COKHI",
                            NamSinh = 2002,
                            QueQuan = "Khanh Hoa"
                        },
                        new
                        {
                            MaSv = 1017,
                            HoTenSv = "Tran Thanh Phuong",
                            MaKhoa = "COKHI",
                            NamSinh = 2003,
                            QueQuan = "Ninh Thuan"
                        },
                        new
                        {
                            MaSv = 1018,
                            HoTenSv = "Le Hoai Phong",
                            MaKhoa = "COKHI",
                            NamSinh = 2001,
                            QueQuan = "Binh Thuan"
                        },
                        new
                        {
                            MaSv = 1019,
                            HoTenSv = "Vo Thi Quynh",
                            MaKhoa = "COKHI",
                            NamSinh = 2002,
                            QueQuan = "Gia Lai"
                        },
                        new
                        {
                            MaSv = 1020,
                            HoTenSv = "Pham Cong Son",
                            MaKhoa = "COKHI",
                            NamSinh = 2004,
                            QueQuan = "Dak Lak"
                        },
                        new
                        {
                            MaSv = 1021,
                            HoTenSv = "Do Thi Thu",
                            MaKhoa = "VCNMT",
                            NamSinh = 2001,
                            QueQuan = "Lam Dong"
                        },
                        new
                        {
                            MaSv = 1022,
                            HoTenSv = "Ngo Bao Tram",
                            MaKhoa = "VCNMT",
                            NamSinh = 2002,
                            QueQuan = "Binh Duong"
                        },
                        new
                        {
                            MaSv = 1023,
                            HoTenSv = "Hoang Gia Tuan",
                            MaKhoa = "VCNMT",
                            NamSinh = 2003,
                            QueQuan = "Dong Nai"
                        },
                        new
                        {
                            MaSv = 1024,
                            HoTenSv = "Phan Thi Uyen",
                            MaKhoa = "VCNMT",
                            NamSinh = 2002,
                            QueQuan = "Tay Ninh"
                        },
                        new
                        {
                            MaSv = 1025,
                            HoTenSv = "Bui Minh Vu",
                            MaKhoa = "VCNMT",
                            NamSinh = 2004,
                            QueQuan = "TP HCM"
                        },
                        new
                        {
                            MaSv = 1026,
                            HoTenSv = "Tran Anh Vy",
                            MaKhoa = "CNTT",
                            NamSinh = 2001,
                            QueQuan = "Can Tho"
                        },
                        new
                        {
                            MaSv = 1027,
                            HoTenSv = "Nguyen Hai Yen",
                            MaKhoa = "TCKT",
                            NamSinh = 2002,
                            QueQuan = "An Giang"
                        },
                        new
                        {
                            MaSv = 1028,
                            HoTenSv = "Pham Duc Anh",
                            MaKhoa = "CNHH",
                            NamSinh = 2003,
                            QueQuan = "Kien Giang"
                        },
                        new
                        {
                            MaSv = 1029,
                            HoTenSv = "Le Thi Bao Chau",
                            MaKhoa = "COKHI",
                            NamSinh = 2001,
                            QueQuan = "Vinh Long"
                        },
                        new
                        {
                            MaSv = 1030,
                            HoTenSv = "Vo Minh Duy",
                            MaKhoa = "VCNMT",
                            NamSinh = 2002,
                            QueQuan = "Ben Tre"
                        });
                });

            modelBuilder.Entity("InternshipManagement.Models.GiangVien", b =>
                {
                    b.HasOne("InternshipManagement.Models.Khoa", "Khoa")
                        .WithMany("GiangViens")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("InternshipManagement.Models.HuongDan", b =>
                {
                    b.HasOne("InternshipManagement.Models.DeTai", "DeTai")
                        .WithMany("HuongDans")
                        .HasForeignKey("MaDt")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternshipManagement.Models.GiangVien", "GiangVien")
                        .WithMany("HuongDans")
                        .HasForeignKey("MaGv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternshipManagement.Models.SinhVien", "SinhVien")
                        .WithMany("HuongDans")
                        .HasForeignKey("MaSv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeTai");

                    b.Navigation("GiangVien");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("InternshipManagement.Models.SinhVien", b =>
                {
                    b.HasOne("InternshipManagement.Models.Khoa", "Khoa")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("InternshipManagement.Models.DeTai", b =>
                {
                    b.Navigation("HuongDans");
                });

            modelBuilder.Entity("InternshipManagement.Models.GiangVien", b =>
                {
                    b.Navigation("HuongDans");
                });

            modelBuilder.Entity("InternshipManagement.Models.Khoa", b =>
                {
                    b.Navigation("GiangViens");

                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("InternshipManagement.Models.SinhVien", b =>
                {
                    b.Navigation("HuongDans");
                });
#pragma warning restore 612, 618
        }
    }
}
